### ISSUE TITLE
Add multi material upgrade

### ISSUE THREAD

**Issue by janknieling** [fab-machines/BigFDM#1]
Hi,

I think it will be a very nice/useful feature to have a multi material upgrade kit like for the prusa i3/the possibility to print with multiple filaments/colours at the same time.

Maybe the MMU2 for the prusa i3 MK3S can be a good template...  
https://shop.prusa3d.com/en/printer-upgrades/183-original-prusa-i3-mk3-multi-material-upgrade-kit.html

https://github.com/prusa3d/Original-Prusa-i3/tree/MMU2

**Comment by satshas** [comment]
Hello,

sorry, this issue must have been missed!

You're absolutely right that with such big area multi material is a nice-to-have feature.
In the next version of the machine we will try implement something similar.

Thanks,
Daniele
