### ISSUE TITLE
Any design update

### ISSUE THREAD

**Issue by ndkazu** [fab-machines/BigFDM#2]
Hello,
I am planning to build this printer with some of my colleagues.
It would really be nice if you had some advice or design updates/improvements to suggest.
also, for the 3d model, is it possible to have a more common format? (igs, stp,etc.. )
cordially,
Kazunobu

**Comment by satshas** [comment]
Hello,

a new version of the machine has been developed, overcoming many of the initial issues, and finally offering a cubic meter printing area.

We hope that by the end of this year we could start release some updates.

Stay tuned!

All the best,
Daniele
